alias python38="docker run -it --rm --name py38 -v "$PWD":/usr/src/myapp -w /usr/src/myapp python:3.8.11-alpine python"
alias python39="docker run -it --rm --name py39 -v "$PWD":/usr/src/myapp -w /usr/src/myapp python:3.9.6-alpine python"
alias python310="docker run -it --rm --name py310 -v "$PWD":/usr/src/myapp -w /usr/src/myapp python:3.10.0b3-alpine python"
alias ffdev="~/.local/firefox-dev/firefox"
alias nu="~/.local/nu_0_23_0_linux/nushell-0.23.0/nu"
